

DROP TABLE IF EXISTS archive;
DROP TABLE IF EXISTS post;

CREATE TABLE archive (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  archivename TEXT UNIQUE NOT NULL,
  password TEXT DEFAULT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES archive (id)
);

